### PR TITLE
Only build CDTs for the current arch

### PR DESCRIPTION
**Pull request by jayfurmanek**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/master/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/master/doc/)?
- [ ] Did you write any [tests](https://github.com/open-ce/open-ce/blob/master/tests/) to validate this change?  

## Description

The adds some arch switches for the config so that CDT packages are only built for the current arch.

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Review by bnemanich — APPROVED** [review]

**Comment by bnemanich** [comment]
Optional tests are failing because the build numbers were not updated. However, since the actual recipes aren't being changed, I don't think the build numbers need to be updated.

**Comment by jayfurmanek** [comment]
Yup, agreed. I can just force this in when we're ready.

**Comment by bnemanich** [comment]
You should be able to merge it now.

**Comment by npanpaliya** [comment]
I think we should also add the arch tags in config/conda_build_config.yaml for the centos_urls. We can also have a single variable `centos_url` and have different values for it based on architecture. But since this is merged now, I'll do this and create a new PR for this.

**Pull request merged**
